INSERT [dbo].[blind_box_categories] ([category_name], [description], [price_range], [rarity_level]) VALUES ( N'Fantasy', N'Mystical creatures, wizards, and legendary beings.', N'$10 - $60', N'Common to Ultra Rare')
INSERT [dbo].[blind_box_categories] ( [category_name], [description], [price_range], [rarity_level]) VALUES ( N'Gaming', N'Blind boxes featuring characters from popular video games.', N'$25 - $70', N'Common to Epic')
INSERT [dbo].[blind_box_categories] ( [category_name], [description], [price_range], [rarity_level]) VALUES ( N'Sci-Fi', N'Space, futuristic themes, and robotic collectibles.', N'$30 - $80', N'Rare to Legendary')
INSERT [dbo].[blind_box_categories] ( [category_name], [description], [price_range], [rarity_level]) VALUES ( N'Anime', N'Popular anime characters and themed mystery figures.', N'$15 - $100', N'Common to Legendary')
INSERT [dbo].[blind_box_categories] ( [category_name], [description], [price_range], [rarity_level]) VALUES ( N'Steampunk', N'Victorian-era inspired mechanical and fantasy figures.', N'$100 - $190', N'Rare to Epic')
INSERT [dbo].[blind_boxes] ( [category_id], [price], [release_date], [stock], [name], [rarity]) VALUES ( 1, 29.99, CAST(N'2024-01-15' AS Date), 150, N'Mystic Creatures Series 1', N'Rare')
INSERT [dbo].[blind_boxes] ( [category_id], [price], [release_date], [stock], [name], [rarity]) VALUES ( 2, 49.99, CAST(N'2023-11-20' AS Date), 75, N'Cyberpunk Warriors', N'Ultra Rare')
INSERT [dbo].[blind_boxes] ( [category_id], [price], [release_date], [stock], [name], [rarity]) VALUES ( 3, 19.99, CAST(N'2024-02-10' AS Date), 200, N'Fantasy Legends', N'Common')
INSERT [dbo].[blind_boxes] ( [category_id], [price], [release_date], [stock], [name], [rarity]) VALUES ( 4, 59.99, CAST(N'2023-12-05' AS Date), 50, N'Space Explorers', N'Epic')
INSERT [dbo].[blind_boxes] ( [category_id], [price], [release_date], [stock], [name], [rarity]) VALUES ( 5, 99.99, CAST(N'2024-03-01' AS Date), 25, N'Neon Anime Stars', N'Legendary')
INSERT [dbo].[blind_boxes] ( [category_id], [price], [release_date], [stock], [name], [rarity]) VALUES ( 2, 24.99, CAST(N'2024-01-30' AS Date), 180, N'Retro Arcade Heroes', N'Common')
INSERT [dbo].[blind_boxes] ( [category_id], [price], [release_date], [stock], [name], [rarity]) VALUES ( 3, 54.99, CAST(N'2023-10-10' AS Date), 60, N'Mythical Beasts Collection', N'Ultra Rare')
